export const siteConfig = {
  name: "Dokter Spesial",
  url: "https://dokterspesial.id",
  description: "Empower Medical Specialists To The Next Level. Platform pembelajaran medis terdepan untuk dokter spesialis. Akses artikel, pelatihan berkelanjutan, dan update perkembangan medis terkini untuk praktik klinis yang lebih baik.",
  tagline: "Empower Medical Specialists To The Next Level",
  subtitle: "Menjadi Dokter Spesialis Terbaik",
  keywords: [
    "empower medical specialists",
    "empower medical specialists to the next level",
    "dokter spesial",
    "dokter spesialis",
    "dokter dentist",
    "global pain academy",
    "GPA",
    "mentor global pain academy",
    "mentor dokter dentist",
    "mentor expert",
    "mentor medis",
    "pelatihan medis",
    "pelatihan berkelanjutan",
    "praktik klinis",
    "perkembangan medis",
    "pendidikan kedokteran",
    "layanan kesehatan berkualitas",
    "artikel medis",
    "blog dokter",
    "update medis terkini",
    "pendidikan dokter spesialis",
    "platform pembelajaran medis",
    "teknologi kesehatan",
    "continuing medical education",
    "medical education platform",
    "specialist doctor training",
    "clinical practice improvement",
    "pain management training",
    "dental specialist",
    "dokter gigi spesialis",
    "instruktur medis expert",
  ],
  email: "support@dokterspesial.id",
  phone: "+62-858-0879-3947",
  address: {
    locality: "Indonesia",
    country: "ID",
  },
  links: {
    instagram: "https://instagram.id/dokterspesial",
    twitter: "https://x.id/dokterspesial",
    tiktok: "https://tiktok.id/@dokterspesial",
  },
  ogImage: "/logo/logo-1.webp",
  logo: "/logo/logo-1.webp",
  blog: {
    title: "Blog Dokter Spesial",
    description: "Artikel, berita, dan update terkini seputar dunia kedokteran, pelatihan medis, dan perkembangan praktik klinis untuk dokter spesialis Indonesia.",
  },
};

export type SiteConfig = typeof siteConfig;
