export interface Event {
  id: number
  title: string
  date: string
  time: string
  category: string
  categoryName: string
  image: string
  url: string
  color: string
  status?: "akan datang" | "berlangsung" | "selesai"
}

export const CALENDAR_EVENTS: Event[] = [
  // October 2025 events for testing
  {
    id: 6001,
    title: "Webinar SKP Kemenkes: Manajemen Diabetes Terkini",
    date: "2025-10-05T09:00:00+07:00",
    time: "09:00 - 11:00",
    category: "akan datang",
    categoryName: "Akan Datang",
    image: "https://storage.googleapis.com/dokterpost-blog/diabetes-management.png",
    url: "https://dokterpost.com/service/webinar-diabetes-management",
    color: "bg-blue-500",
    status: "akan datang",
  },
  {
    id: 6002,
    title: "Workshop Penanganan Hipertensi",
    date: "2025-10-10T14:00:00+07:00",
    time: "14:00 - 16:00",
    category: "berlangsung",
    categoryName: "Sedang Berlangsung",
    image: "/placeholder/hypertension-workshop.png",
    url: "#",
    color: "bg-orange-500",
    status: "berlangsung",
  },
  {
    id: 6003,
    title: "Seminar Kesehatan Mental",
    date: "2025-10-15T08:30:00+07:00",
    time: "08:30 - 10:30",
    category: "akan datang",
    categoryName: "Akan Datang",
    image: "/placeholder/mental-health-seminar.png",
    url: "#",
    color: "bg-blue-500",
    status: "akan datang",
  },
  {
    id: 6004,
    title: "Workshop Terapi Fisik",
    date: "2025-10-20T13:00:00+07:00",
    time: "13:00 - 15:00",
    category: "selesai",
    categoryName: "Selesai",
    image: "/placeholder/physical-therapy.png",
    url: "#",
    color: "bg-gray-500",
    status: "selesai",
  },
  {
    id: 6005,
    title: "Webinar Pencegahan Penyakit Jantung",
    date: "2025-10-25T10:00:00+07:00",
    time: "10:00 - 12:00",
    category: "akan datang",
    categoryName: "Akan Datang",
    image: "/placeholder/heart-disease-prevention.png",
    url: "#",
    color: "bg-blue-500",
    status: "akan datang",
  },
  // Original September events
  {
    id: 5869,
    title: "Webinar SKP Kemenkes: Hiperglikemia pada Situasi Emergensi",
    date: "2025-09-06T08:00:00+07:00",
    time: "08:00 - 10:00",
    category: "akan datang",
    categoryName: "Akan Datang",
    image: "https://storage.googleapis.com/dokterpost-blog/Hipergilkemia-pada-situasi-emergensi-06-September.png",
    url: "https://dokterpost.com/service/webinar-skp-kemenkes-hiperglikemia-pada-situasi-emergensi",
    color: "bg-blue-500",
    status: "akan datang",
  },
  {
    id: 5870,
    title: "Workshop Diabetes Management",
    date: "2025-09-06T14:00:00+07:00",
    time: "14:00 - 16:00",
    category: "berlangsung",
    categoryName: "Sedang Berlangsung",
    image: "/placeholder/diabetes-workshop.png",
    url: "#",
    color: "bg-orange-500",
    status: "berlangsung",
  },
  {
    id: 5965,
    title: "Webinar SKP Kemenkes: On Emergency Medical Services at Hajj",
    date: "2025-09-17T08:00:00+07:00",
    time: "08:00 - 10:00",
    category: "akan datang",
    categoryName: "Akan Datang",
    image: "/placeholder/medical-emergency-services-webinar.png",
    url: "https://dokterpost.com/service/webinar-skp-kemenkes-on-emergency-medical-services-at-hajj",
    color: "bg-blue-500",
    status: "akan datang",
  },
  {
    id: 5972,
    title: "Workshop Manajemen Stres",
    date: "2025-09-17T14:00:00+07:00",
    time: "14:00 - 16:00",
    category: "selesai",
    categoryName: "Selesai",
    image: "/placeholder/diabetes-workshop.png",
    url: "#",
    color: "bg-gray-500",
    status: "selesai",
  },
  {
    id: 5966,
    title: "Webinar SKP Kemenkes: Tatalaksana Komprehensif pada Nyeri Lutut",
    date: "2025-09-13T08:00:00+07:00",
    time: "08:00 - 10:00",
    category: "akan datang",
    categoryName: "Akan Datang",
    image: "/placeholder/knee-pain-management-webinar.png",
    url: "https://dokterpost.com/service/webinar-skp-kemenkes-tatalaksana-komprehensif-pada-nyeri-lutut",
    color: "bg-blue-500",
    status: "akan datang",
  },
  {
    id: 5974,
    title: "Workshop Komunikasi Efektif",
    date: "2025-09-13T15:00:00+07:00",
    time: "15:00 - 17:00",
    category: "berlangsung",
    categoryName: "Sedang Berlangsung",
    image: "/placeholder/diabetes-workshop.png",
    url: "#",
    color: "bg-orange-500",
    status: "berlangsung",
  },
  {
    id: 5967,
    title: "Workshop Manajemen Diabetes",
    date: "2025-09-20T14:00:00+07:00",
    time: "14:00 - 16:00",
    category: "selesai",
    categoryName: "Selesai",
    image: "/placeholder/diabetes-workshop.png",
    url: "#",
    color: "bg-gray-500",
    status: "selesai",
  },
  {
    id: 5976,
    title: "Webinar Pencegahan Penyakit",
    date: "2025-09-20T09:00:00+07:00",
    time: "09:00 - 11:00",
    category: "akan datang",
    categoryName: "Akan Datang",
    image: "/placeholder/medical-emergency-services-webinar.png",
    url: "#",
    color: "bg-blue-500",
    status: "akan datang",
  },
  {
    id: 5978,
    title: "Workshop Terapi Fisik",
    date: "2025-09-24T14:30:00+07:00",
    time: "14:30 - 16:30",
    category: "berlangsung",
    categoryName: "Sedang Berlangsung",
    image: "/placeholder/diabetes-workshop.png",
    url: "#",
    color: "bg-orange-500",
    status: "berlangsung",
  },
  {
    id: 5979,
    title: "Webinar Inovasi Medis",
    date: "2025-09-24T19:00:00+07:00",
    time: "19:00 - 21:00",
    category: "selesai",
    categoryName: "Selesai",
    image: "/placeholder/medical-emergency-services-webinar.png",
    url: "#",
    color: "bg-gray-500",
    status: "selesai",
  },
];

export const MONTH_NAMES = [
  "Januari",
  "Februari",
  "Maret",
  "April",
  "Mei",
  "Juni",
  "Juli",
  "Agustus",
  "September",
  "Oktober",
  "November",
  "Desember",
];

export const DAY_NAMES = ["Min", "Sen", "Sel", "Rab", "Kam", "Jum", "Sab"];

export const PROGRAM_FILTERS = [
  { value: "berlangsung,akan datang", label: "Program" },
  { value: "akan datang", label: "Akan Datang" },
  { value: "berlangsung", label: "Sedang Berlangsung" },
  { value: "selesai", label: "Selesai" },
];
